# permissions for end users to edit memcacheds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: memcached-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-memcached
    app.kubernetes.io/part-of: kubebuilder-memcached
    app.kubernetes.io/managed-by: kustomize
  name: memcached-editor-role
rules:
- apiGroups:
  - example.com.tyler.gabb.domain
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com.tyler.gabb.domain
  resources:
  - memcacheds/status
  verbs:
  - get
